name: "Scan secrets - without a full history scan"
description: "Scan secrets - without a full history scan"

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      BASE_BRANCH_NAME: ${{ github.base_ref }}
      FEATURE_BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: "Install Gitleaks"
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz
          tar -xvf gitleaks_8.24.3_linux_x64.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/
      - name: "Run secret scanning"
        run: |
          COMPARE_RESPONSE=$(gh api repos/${GH_REPO}/compare/${BASE_BRANCH_NAME}...${FEATURE_BRANCH_NAME})
          BASE_COMMIT=$(jq -r '.merge_base_commit.sha' <<< $COMPARE_RESPONSE)
          NUMBER_OF_COMMITS=$(jq -r '.total_commits' <<< $COMPARE_RESPONSE)
          git fetch --no-tags --prune --depth=$NUMBER_OF_COMMITS origin $FEATURE_BRANCH_NAME
          git checkout -B $FEATURE_BRANCH_NAME origin/$FEATURE_BRANCH_NAME
          git log --oneline
          pwd
          ls
          cat random_files/a_file_with_stuff.txt
          gitleaks detect --log-opts="${BASE_COMMIT}..HEAD" --verbose --redact
